# -*- coding: utf-8 -*-
"""personalintro.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvik3cIkkJa2mAl1rKCK6rrz_XAWoGhP
"""

a=input("What is your name?\n")
b=int(input("how old are you?\n"))
c=input("What is your favorite hobby?\n")
d=input("What is your comfort meal?\n")
print(f"\n🎊Welcome {a}🎊\nYou are {b} years old and your favourite hobby is {c} and your comfy meal is {d}\nHave a good day!😊")